name = "cloudflare-ddns"
main = "src/index.ts"
compatibility_date = "2022-11-04"

[vars]
API_TOKEN = "YOUR_API_TOKEN"
ZONE_IDENTIFIER = "YOUR_ZONE_ID"
ENTRYPOINT = "/YOUR_ENTRYPOINT_HERE"
CLIENT_TOKEN = "YOUR_CLIENT_TOKEN"
